site_name: REDHBR - Repositório Digital das Humanidades (pt-BR)
site_url: https://LABHDUFBA.github.io/redhbr

theme:
  logo: img/logo.jpg
  favicon: img/favicon.ico
  name: material 
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Mudar para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Mudar para modo noturno

repo_url: https://github.com/LABHDUFBA/redhbr
repo_name: LABHDUFBA/redhbr

plugins:
  - git-revision-date

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.superfences

nav:
    - Home: index.md
    - Anpuh: anpuh.md
    - Anpocs: anpocs.md
    - Anped: anped.md
    - Compos: compos.md
    - Scielo.br: scielo.md
    - Autores: authors.md
    - Citação: citation.md
    - Licença: license.md 
